language: generic

services:
  - docker

before_install:
  - docker build -t adhupraba/ott-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true adhupraba/ott-test npm run test
  
after_success:
  - docker build -t adhupraba/ott-client ./client
  - docker build -t adhupraba/ott-nginx ./nginx
  - docker build -t adhupraba/ott-server ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push adhupraba/ott-client
  - docker push adhupraba/ott-nginx
  - docker push adhupraba/ott-server
  
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "ciniscape"
  env: "Ciniscape-env-1"
  bucket_name: "elasticbeanstalk-ap-south-1-156087891586"
  bucket_path: "ciniscape"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY